// Tall-viewport captures (restored fixture run) so the Inspector + Pre-flight Brief are fully visible.
import { chromium } from "@playwright/test";
const BASE = process.env.BASE ?? "http://localhost:3100";
const OUT = "brag-output/composition/assets/ui";
const browser = await chromium.launch({ channel: "chrome", headless: true, args: ["--use-gl=angle", "--use-angle=metal"] });
const ctx = await browser.newContext({ viewport: { width: 1440, height: 1100 }, deviceScaleFactor: 2, colorScheme: "dark" });
const page = await ctx.newPage();
const shot = (name) => page.screenshot({ path: `${OUT}/${name}.png` });
await page.goto(BASE + "/");
await page.getByText("Synthetic Attention Laboratory").waitFor();
await page.getByRole("button", { name: /Run on development fixture/ }).click();
const badge = page.getByText("DEV FIXTURE · NOT ORIANE OUTPUT");
await badge.waitFor({ timeout: 60000 });
await page.waitForTimeout(2500);
await page.keyboard.press("1");
await page.getByText(/^ATTENTION FRACTURE /).waitFor();
await page.waitForTimeout(1200);
await shot("T05-fracture-f1");
await page.getByRole("button", { name: "Simulate patch" }).first().click();
await page.getByText(/^COUNTERFACTUAL · /).waitFor();
await page.getByText(/[+−-]?\d+\.\d pts/).first().waitFor();
await page.waitForTimeout(1500);
await shot("T07-counterfactual");
await page.keyboard.press("Escape");
await page.getByTestId("brief-toggle").click();
const brief = page.getByTestId("preflight-brief");
await brief.waitFor();
await page.waitForTimeout(900);
await shot("T08-brief");
const sim = brief.getByTestId("brief-simulate");
if (await sim.isVisible()) await sim.click();
await brief.getByTestId("brief-result").waitFor({ timeout: 30000 });
await page.waitForTimeout(1500);
await shot("T09-brief-result");
await brief.screenshot({ path: `${OUT}/T09-brief-panel.png` });
// scrolled-to-bottom version at 16:9
await page.setViewportSize({ width: 1440, height: 810 });
await page.waitForTimeout(800);
await brief.evaluate((el) => { const sc = [el, ...el.querySelectorAll("*")].find((n) => n.scrollHeight > n.clientHeight + 20); if (sc) sc.scrollTop = sc.scrollHeight; });
await page.waitForTimeout(600);
await shot("09-brief-result-bottom");
await browser.close();
